name: NodeJS
on:
  push:
    branches:
    - master
    tags:
    - 'v*'
  pull_request:
    branches:
    - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16, 18, 20]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.17'
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - name: Install node-gyp
      run: npm install -g node-gyp
    - name: Build from source
      run: |
        cd bindings/js
        npm --version
        node --version
        npm ci --build-from-source
        npm test

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.17'
    - uses: actions/setup-node@v4
    - name: Install node-gyp and prebuildify
      run: npm install --location=global node-gyp node-gyp-build node-api-headers prebuildify
    - name: Install dependencies
      run: |
        cd bindings/js
        npm install node-gyp-build node-api-headers
    - name: Build
      run: make -C bindings/js
    - name: Directory
      run: ls -R
    - name: Test
      run: |
        cd bindings/js
        npm test
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}.node
        path: bindings/js/prebuilds/*/*.node
